import { compare, hash } from "bcryptjs";
import { ApplicationError } from "@/shared/errors/application-error";
import type { PaginationInput } from "@/shared/types/pagination";
import { cleanText } from "@/shared/utils/text";
import { userRepository } from "../infrastructure/user-repository";
import { passwordSchema, profileSchema, userSchema } from "../schemas/user-schema";

export const userService = {
  list: (input?: PaginationInput & { role?: "SUPER_ADMIN" | "ADMIN" | "STUDENT" }) => userRepository.list(input), findById: (id: string) => userRepository.findById(id), countStudents: () => userRepository.countStudents(), recentStudents: (limit?: number) => userRepository.recentStudents(limit),
  async save(raw: unknown, actor: { id: string; role: string }) { const parsed = userSchema.safeParse(raw); if (!parsed.success) throw new ApplicationError("VALIDATION", "Check the highlighted fields.", parsed.error.flatten().fieldErrors); if (actor.role !== "SUPER_ADMIN" && parsed.data.role !== "STUDENT") throw new ApplicationError("FORBIDDEN", "Only a super administrator can assign administrative roles."); if (parsed.data.id === actor.id && !parsed.data.isActive) throw new ApplicationError("CONFLICT", "You cannot deactivate your own account."); const values = { name: cleanText(parsed.data.name), email: parsed.data.email.toLowerCase(), role: parsed.data.role, isActive: parsed.data.isActive, updatedAt: new Date(), ...(parsed.data.password ? { passwordHash: await hash(parsed.data.password, 12) } : {}) }; try { if (parsed.data.id) { const item = await userRepository.update(parsed.data.id, values); if (!item) throw new ApplicationError("NOT_FOUND", "User not found."); return item; } return userRepository.create({ ...values, passwordHash: await hash(parsed.data.password!, 12) }); } catch (error) { if (typeof error === "object" && error && "code" in error && error.code === "23505") throw new ApplicationError("CONFLICT", "A user with this email already exists."); throw error; } },
  async updateProfile(userId: string, raw: unknown) { const parsed = profileSchema.safeParse(raw); if (!parsed.success) throw new ApplicationError("VALIDATION", "Check the highlighted fields.", parsed.error.flatten().fieldErrors); const item = await userRepository.update(userId, { name: cleanText(parsed.data.name), updatedAt: new Date() }); if (!item) throw new ApplicationError("NOT_FOUND", "User not found."); return item; },
  async changePassword(userId: string, raw: unknown) { const parsed = passwordSchema.safeParse(raw); if (!parsed.success) throw new ApplicationError("VALIDATION", "Check the highlighted fields.", parsed.error.flatten().fieldErrors); const user = await userRepository.findById(userId); if (!user || !await compare(parsed.data.currentPassword, user.passwordHash)) throw new ApplicationError("VALIDATION", "Current password is incorrect.", { currentPassword: ["Current password is incorrect"] }); await userRepository.update(userId, { passwordHash: await hash(parsed.data.newPassword, 12), updatedAt: new Date() }); },
};
