"use client";

import { Checkbox, Paper, Radio, Stack, Text } from "@mantine/core";
import { IconCheck, IconX } from "@tabler/icons-react";
import type { LearnerSessionQuestion } from "@/modules/study/types/session-types";

export function QuestionRenderer({ question, selected, onChange, disabled }: { question: LearnerSessionQuestion; selected: string[]; onChange: (ids: string[]) => void; disabled: boolean }) {
  const feedback = question.feedback;
  return <Stack gap="sm" className="session-answer-list">{question.options.map((option) => { const isSelected = selected.includes(option.id); const correct = feedback?.correctOptionIds.includes(option.id); const wrongSelected = Boolean(feedback && isSelected && !correct); const toggle = () => { if (disabled) return; if (question.type === "multiple_choice") onChange(isSelected ? selected.filter((id) => id !== option.id) : [...selected, option.id]); else onChange([option.id]); }; return <Paper key={option.id} withBorder p={{ base: "sm", sm: "md" }} bg={correct ? "green.0" : wrongSelected ? "red.0" : isSelected ? "blue.0" : "white"} style={{ cursor: disabled ? "default" : "pointer", borderColor: correct ? "var(--mantine-color-green-5)" : wrongSelected ? "var(--mantine-color-red-5)" : isSelected ? "var(--mantine-color-blue-5)" : undefined }} onClick={toggle} role="button" aria-disabled={disabled} data-haptic="selection" tabIndex={disabled ? -1 : 0} onKeyDown={(event) => { if (event.key === " " || event.key === "Enter") { event.preventDefault(); toggle(); } }}><Stack gap={0}><div style={{ display: "flex", alignItems: "center", gap: 12 }}>{question.type === "multiple_choice" ? <Checkbox checked={isSelected} readOnly aria-label={option.text} /> : <Radio checked={isSelected} readOnly aria-label={option.text} />}<Text style={{ flex: 1 }}>{option.text}</Text>{correct && <IconCheck size={20} color="var(--mantine-color-green-7)" />}{wrongSelected && <IconX size={20} color="var(--mantine-color-red-7)" />}</div></Stack></Paper>; })}</Stack>;
}
