"use client";

import { Accordion, Badge, Grid, Group, Paper, Stack, Table, Text, Title } from "@mantine/core";
import { IconCircleCheck, IconCircleX, IconClipboardList, IconClockHour4, IconPlayerSkipForward, IconTargetArrow } from "@tabler/icons-react";
import { StatCard } from "@/shared/ui/stat-card";
import { formatDuration, formatPercent } from "@/shared/utils/text";
import type { SessionSummaryData } from "../application/summary-service";

type Summary = SessionSummaryData;
function PerformanceTable({ title, rows }: { title: string; rows: Summary["subjectPerformance"] }) { return <Paper className="tabler-card" p="lg"><Title order={3} fz="md" mb="md">{title}</Title><Table><Table.Thead><Table.Tr><Table.Th>Area</Table.Th><Table.Th>Correct</Table.Th><Table.Th>Accuracy</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{rows.map((row) => <Table.Tr key={row.label}><Table.Td>{row.label}</Table.Td><Table.Td>{row.correct}/{row.attempted}</Table.Td><Table.Td>{formatPercent(row.accuracy)}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Paper>; }
export function SessionSummary({ summary }: { summary: Summary }) { return <Stack gap="lg"><Grid>{[{ label: "Total questions", value: summary.total, icon: IconClipboardList, color: "blue" }, { label: "Correct", value: summary.correct, icon: IconCircleCheck, color: "green" }, { label: "Incorrect", value: summary.incorrect, icon: IconCircleX, color: "red" }, { label: "Skipped", value: summary.skipped, icon: IconPlayerSkipForward, color: "gray" }, { label: "Accuracy", value: formatPercent(summary.accuracy), icon: IconTargetArrow, color: "violet" }, { label: "Total time", value: formatDuration(summary.totalTime), icon: IconClockHour4, color: "cyan" }].map((item) => <Grid.Col key={item.label} span={{ base: 12, sm: 6, lg: 4 }}><StatCard {...item} /></Grid.Col>)}</Grid><Grid><Grid.Col span={{ base: 12, lg: 4 }}><PerformanceTable title="Subject performance" rows={summary.subjectPerformance} /></Grid.Col><Grid.Col span={{ base: 12, lg: 4 }}><PerformanceTable title="Topic performance" rows={summary.topicPerformance} /></Grid.Col><Grid.Col span={{ base: 12, lg: 4 }}><PerformanceTable title="Difficulty performance" rows={summary.difficultyPerformance} /></Grid.Col></Grid><Paper className="tabler-card" p="lg"><Title order={3} fz="md" mb="md">Review answers</Title><Accordion variant="separated">{summary.review.map((item) => <Accordion.Item key={item.order} value={String(item.order)}><Accordion.Control><Group><Badge color={item.isSkipped ? "gray" : item.isCorrect ? "green" : "red"}>{item.isSkipped ? "Skipped" : item.isCorrect ? "Correct" : "Incorrect"}</Badge><Text lineClamp={1}>Question {item.order}: {item.prompt}</Text></Group></Accordion.Control><Accordion.Panel><Stack><Text className="question-copy" fw={600}>{item.prompt}</Text>{item.options.map((option) => { const selected = item.selectedOptionIds.includes(option.id); return <Paper key={option.id} withBorder p="sm" bg={option.isCorrect ? "green.0" : selected ? "red.0" : undefined}><Group justify="space-between"><Text>{option.text}</Text><Text fz="xs" fw={600}>{option.isCorrect ? "Correct answer" : selected ? "Your answer" : ""}</Text></Group></Paper>; })}<Text c="dimmed" className="question-copy">{item.explanation || "No explanation provided."}</Text></Stack></Accordion.Panel></Accordion.Item>)}</Accordion></Paper></Stack>; }
