import { and, asc, count, countDistinct, eq, gte, isNull, lte, sql } from "drizzle-orm";
import { db } from "@/infrastructure/database/client";
import { attempts, questions, studySessions, subjects, topics } from "@/infrastructure/database/schema";
import type { ProgressFilters } from "../schemas/progress-schema";

function attemptConditions(userId: string, filters: ProgressFilters, includeSkipped = true) { return [eq(attempts.userId, userId), includeSkipped ? undefined : eq(attempts.isSkipped, false), filters.examId ? eq(questions.examId, filters.examId) : undefined, filters.subjectId ? eq(questions.subjectId, filters.subjectId) : undefined, filters.from ? gte(attempts.answeredAt, new Date(`${filters.from}T00:00:00.000Z`)) : undefined, filters.to ? lte(attempts.answeredAt, new Date(`${filters.to}T23:59:59.999Z`)) : undefined].filter(Boolean) as ReturnType<typeof eq>[]; }
export const progressRepository = {
  async metrics(userId: string, filters: ProgressFilters) { const answerFilter = and(...attemptConditions(userId, filters, false)); const allFilter = and(...attemptConditions(userId, filters, true)); const sessionConditions = [eq(studySessions.userId, userId), eq(studySessions.status, "completed"), filters.examId ? eq(studySessions.examId, filters.examId) : undefined, filters.subjectId ? eq(studySessions.subjectId, filters.subjectId) : undefined, filters.from ? gte(studySessions.completedAt, new Date(`${filters.from}T00:00:00.000Z`)) : undefined, filters.to ? lte(studySessions.completedAt, new Date(`${filters.to}T23:59:59.999Z`)) : undefined].filter(Boolean) as ReturnType<typeof eq>[]; const [[answers], [time], [sessions]] = await Promise.all([db.select({ attempted: count(), uniqueQuestions: countDistinct(attempts.questionId), correct: sql<number>`count(*) filter (where ${attempts.isCorrect} = true)::int`, incorrect: sql<number>`count(*) filter (where ${attempts.isCorrect} = false)::int` }).from(attempts).innerJoin(questions, eq(attempts.questionId, questions.id)).where(answerFilter), db.select({ studyTime: sql<number>`coalesce(sum(${attempts.responseTimeSeconds}), 0)::int` }).from(attempts).innerJoin(questions, eq(attempts.questionId, questions.id)).where(allFilter), db.select({ total: count() }).from(studySessions).where(and(...sessionConditions))]); return { ...answers, studyTime: time.studyTime, totalSessions: sessions.total }; },
  async subjectPerformance(userId: string, filters: ProgressFilters) { return db.select({ id: subjects.id, label: subjects.name, attempted: count(), correct: sql<number>`count(*) filter (where ${attempts.isCorrect} = true)::int` }).from(attempts).innerJoin(questions, eq(attempts.questionId, questions.id)).innerJoin(subjects, eq(questions.subjectId, subjects.id)).where(and(...attemptConditions(userId, filters, false))).groupBy(subjects.id, subjects.name).orderBy(asc(subjects.name)); },
  async topicPerformance(userId: string, filters: ProgressFilters) { return db.select({ id: topics.id, label: topics.name, attempted: count(), correct: sql<number>`count(*) filter (where ${attempts.isCorrect} = true)::int` }).from(attempts).innerJoin(questions, eq(attempts.questionId, questions.id)).innerJoin(topics, eq(questions.topicId, topics.id)).where(and(...attemptConditions(userId, filters, false))).groupBy(topics.id, topics.name).orderBy(asc(topics.name)); },
  async dailyActivity(userId: string, filters: ProgressFilters) { const since = filters.from ? new Date(`${filters.from}T00:00:00.000Z`) : new Date(Date.now() - 29 * 24 * 60 * 60 * 1000); return db.select({ date: sql<string>`to_char(${attempts.answeredAt} at time zone 'UTC', 'YYYY-MM-DD')`, attempted: sql<number>`count(*) filter (where ${attempts.isSkipped} = false)::int`, correct: sql<number>`count(*) filter (where ${attempts.isCorrect} = true)::int`, seconds: sql<number>`coalesce(sum(${attempts.responseTimeSeconds}), 0)::int` }).from(attempts).innerJoin(questions, eq(attempts.questionId, questions.id)).where(and(...attemptConditions(userId, { ...filters, from: undefined }, true), gte(attempts.answeredAt, since))).groupBy(sql`to_char(${attempts.answeredAt} at time zone 'UTC', 'YYYY-MM-DD')`).orderBy(sql`to_char(${attempts.answeredAt} at time zone 'UTC', 'YYYY-MM-DD')`); },
  async subjectOverview(userId: string, examId?: string) { const filter = and(eq(subjects.isActive, true), examId ? eq(subjects.examId, examId) : undefined); return db.select({ id: subjects.id, name: subjects.name, code: subjects.code, examId: subjects.examId, available: sql<number>`count(distinct ${questions.id}) filter (where ${questions.isActive} = true and ${questions.archivedAt} is null)::int`, attempted: sql<number>`count(${attempts.id}) filter (where ${attempts.isSkipped} = false)::int`, correct: sql<number>`count(${attempts.id}) filter (where ${attempts.isCorrect} = true)::int` }).from(subjects).leftJoin(questions, eq(questions.subjectId, subjects.id)).leftJoin(attempts, and(eq(attempts.questionId, questions.id), eq(attempts.userId, userId))).where(filter).groupBy(subjects.id, subjects.name, subjects.code, subjects.examId).orderBy(asc(subjects.displayOrder), asc(subjects.name)); },
  async availableQuestions(examId?: string) { const conditions = [eq(questions.isActive, true), isNull(questions.archivedAt), examId ? eq(questions.examId, examId) : undefined].filter(Boolean) as ReturnType<typeof eq>[]; const [row] = await db.select({ value: count() }).from(questions).where(and(...conditions)); return row.value; },
};
