"use client";

import { useEffect, useMemo, useTransition } from "react";
import { Alert, Button, Checkbox, Divider, Grid, Group, NumberInput, Paper, Select, Stack, Switch, TagsInput, TextInput, Textarea, Title } from "@mantine/core";
import { useForm } from "@mantine/form";
import { zod4Resolver } from "mantine-form-zod-resolver";
import { notifications } from "@mantine/notifications";
import { IconAlertCircle, IconPlus, IconTrash } from "@tabler/icons-react";
import { useRouter } from "next/navigation";
import type { Exam, Subject, Topic } from "@/infrastructure/database/schema";
import type { QuestionDetail } from "../infrastructure/question-repository";
import { questionSchema } from "../schemas/question-schema";
import { saveQuestionAction } from "./actions";

type FormValues = { id?: string; examId: string; subjectId: string; topicId: string; subtopicId: string | null; type: "single_choice" | "multiple_choice" | "true_false"; prompt: string; options: Array<{ id?: string; text: string; isCorrect: boolean; displayOrder: number }>; explanation: string; difficulty: "easy" | "medium" | "hard"; source: string; reference: string; tags: string[]; estimatedTimeSeconds: number; isActive: boolean };

export function QuestionForm({ question, exams, subjects, topics }: { question?: QuestionDetail; exams: Exam[]; subjects: Subject[]; topics: Topic[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const initialValues: FormValues = question ? { id: question.id, examId: question.examId, subjectId: question.subjectId, topicId: question.topicId, subtopicId: question.subtopicId, type: question.type, prompt: question.prompt, options: question.options.map((option) => ({ id: option.id, text: option.text, isCorrect: option.isCorrect, displayOrder: option.displayOrder })), explanation: question.explanation, difficulty: question.difficulty, source: question.source, reference: question.reference, tags: question.tags, estimatedTimeSeconds: question.estimatedTimeSeconds, isActive: question.isActive } : { examId: exams[0]?.id ?? "", subjectId: "", topicId: "", subtopicId: null, type: "single_choice", prompt: "", options: [{ text: "", isCorrect: true, displayOrder: 0 }, { text: "", isCorrect: false, displayOrder: 1 }], explanation: "", difficulty: "medium", source: "", reference: "", tags: [], estimatedTimeSeconds: 60, isActive: true };
  const form = useForm<FormValues>({ initialValues, validate: zod4Resolver(questionSchema) });
  const availableSubjects = useMemo(() => subjects.filter((subject) => subject.examId === form.values.examId), [subjects, form.values.examId]);
  const availableTopics = useMemo(() => topics.filter((topic) => topic.subjectId === form.values.subjectId && !topic.parentTopicId), [topics, form.values.subjectId]);
  const availableSubtopics = useMemo(() => topics.filter((topic) => topic.parentTopicId === form.values.topicId), [topics, form.values.topicId]);
  useEffect(() => { const listener = (event: BeforeUnloadEvent) => { if (form.isDirty()) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", listener); return () => window.removeEventListener("beforeunload", listener); }, [form]);
  const changeType = (value: string | null) => { const type = (value ?? "single_choice") as FormValues["type"]; form.setFieldValue("type", type); if (type === "true_false") form.setFieldValue("options", [{ text: "True", isCorrect: true, displayOrder: 0 }, { text: "False", isCorrect: false, displayOrder: 1 }]); };
  const setCorrect = (index: number, checked: boolean) => { if (form.values.type === "single_choice" || form.values.type === "true_false") form.setFieldValue("options", form.values.options.map((option, optionIndex) => ({ ...option, isCorrect: optionIndex === index ? checked : false }))); else form.setFieldValue(`options.${index}.isCorrect`, checked); };
  const submit = form.onSubmit((values) => startTransition(async () => { const result = await saveQuestionAction(values); if (result.ok) { notifications.show({ color: "green", message: result.message }); form.resetDirty(); router.push(`/admin/questions/${result.data.id}`); } else { notifications.show({ color: "red", message: result.message }); if (result.fieldErrors) Object.entries(result.fieldErrors).forEach(([field, messages]) => form.setFieldError(field, messages?.[0])); } }));
  return <form onSubmit={submit} noValidate><Stack gap="lg">
    {form.errors.options && <Alert color="red" icon={<IconAlertCircle size={18} />}>{String(form.errors.options)}</Alert>}
    <Paper className="tabler-card" p="lg"><Title order={3} fz="md" mb="md">Classification</Title><Grid><Grid.Col span={{ base: 12, md: 4 }}><Select label="Exam" required searchable data={exams.map((item) => ({ value: item.id, label: item.name }))} value={form.values.examId} onChange={(value) => { form.setFieldValue("examId", value ?? ""); form.setFieldValue("subjectId", ""); form.setFieldValue("topicId", ""); form.setFieldValue("subtopicId", null); }} error={form.errors.examId} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><Select data-testid="question-subject" label="Subject" required searchable data={availableSubjects.map((item) => ({ value: item.id, label: item.name }))} value={form.values.subjectId} onChange={(value) => { form.setFieldValue("subjectId", value ?? ""); form.setFieldValue("topicId", ""); form.setFieldValue("subtopicId", null); }} error={form.errors.subjectId} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><Select data-testid="question-topic" label="Topic" required searchable data={availableTopics.map((item) => ({ value: item.id, label: item.name }))} value={form.values.topicId} onChange={(value) => { form.setFieldValue("topicId", value ?? ""); form.setFieldValue("subtopicId", null); }} error={form.errors.topicId} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><Select label="Subtopic" clearable searchable data={availableSubtopics.map((item) => ({ value: item.id, label: item.name }))} {...form.getInputProps("subtopicId")} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><Select label="Difficulty" required data={[{ value: "easy", label: "Easy" }, { value: "medium", label: "Medium" }, { value: "hard", label: "Hard" }]} {...form.getInputProps("difficulty")} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><Select label="Question type" required data={[{ value: "single_choice", label: "Single choice" }, { value: "multiple_choice", label: "Multiple choice" }, { value: "true_false", label: "True / False" }]} value={form.values.type} onChange={changeType} /></Grid.Col></Grid></Paper>
    <Paper className="tabler-card" p="lg"><Title order={3} fz="md" mb="md">Question and answers</Title><Stack><Textarea label="Question" description="Plain text is sanitized before storage." minRows={5} autosize required {...form.getInputProps("prompt")} /><Divider label="Options" labelPosition="left" />{form.values.options.map((option, index) => <Group key={option.id ?? index} align="flex-start" wrap="nowrap"><Checkbox mt={30} checked={option.isCorrect} onChange={(event) => setCorrect(index, event.currentTarget.checked)} aria-label={`Mark option ${index + 1} correct`} /><TextInput label={`Option ${index + 1}`} required style={{ flex: 1 }} disabled={form.values.type === "true_false"} {...form.getInputProps(`options.${index}.text`)} /><Button variant="subtle" color="red" mt={24} px="xs" disabled={form.values.options.length <= 2 || form.values.type === "true_false"} onClick={() => form.removeListItem("options", index)} aria-label={`Remove option ${index + 1}`}><IconTrash size={18} /></Button></Group>)}{form.values.type !== "true_false" && <Button variant="light" leftSection={<IconPlus size={16} />} onClick={() => form.insertListItem("options", { text: "", isCorrect: false, displayOrder: form.values.options.length })} disabled={form.values.options.length >= 12} w="fit-content">Add option</Button>}<Textarea label="Explanation" minRows={4} autosize {...form.getInputProps("explanation")} /></Stack></Paper>
    <Paper className="tabler-card" p="lg"><Title order={3} fz="md" mb="md">Metadata</Title><Grid><Grid.Col span={{ base: 12, md: 6 }}><TextInput label="Source" {...form.getInputProps("source")} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><TextInput label="Reference" {...form.getInputProps("reference")} /></Grid.Col><Grid.Col span={{ base: 12, md: 8 }}><TagsInput label="Tags" placeholder="Type and press Enter" {...form.getInputProps("tags")} /></Grid.Col><Grid.Col span={{ base: 12, md: 4 }}><NumberInput label="Estimated time (seconds)" min={1} max={3600} required {...form.getInputProps("estimatedTimeSeconds")} /></Grid.Col></Grid><Switch mt="md" label="Active and available for study" {...form.getInputProps("isActive", { type: "checkbox" })} /></Paper>
    <Group justify="flex-end"><Button variant="default" onClick={() => router.push("/admin/questions")}>Cancel</Button><Button type="submit" loading={pending}>Save question</Button></Group>
  </Stack></form>;
}
