import { examRepository } from "@/modules/exams/infrastructure/exam-repository";
import { subjectRepository } from "@/modules/subjects/infrastructure/subject-repository";
import { topicRepository } from "@/modules/topics/infrastructure/topic-repository";
import { ApplicationError } from "@/shared/errors/application-error";
import { ensureSufficientQuestions } from "../domain/session-selection";
import { studyRepository } from "../infrastructure/study-repository";
import { completeSessionSchema, createSessionSchema } from "../schemas/study-schema";
import type { AnswerFeedback, LearnerSession } from "../types/session-types";

export const studyService = {
  async create(userId: string, raw: unknown) { const parsed = createSessionSchema.safeParse(raw); if (!parsed.success) throw new ApplicationError("VALIDATION", "Check the highlighted fields.", parsed.error.flatten().fieldErrors); const [exam, subject, topic] = await Promise.all([examRepository.findById(parsed.data.examId), parsed.data.subjectId ? subjectRepository.findById(parsed.data.subjectId) : null, parsed.data.topicId ? topicRepository.findById(parsed.data.topicId) : null]); if (!exam?.isActive) throw new ApplicationError("VALIDATION", "Select an active exam.", { examId: ["Exam is unavailable"] }); if (parsed.data.subjectId && (!subject?.isActive || subject.examId !== exam.id)) throw new ApplicationError("VALIDATION", "Select an active subject from this exam.", { subjectId: ["Subject is unavailable"] }); if (parsed.data.topicId && (!topic?.isActive || topic.subjectId !== parsed.data.subjectId)) throw new ApplicationError("VALIDATION", "Select an active topic from this subject.", { topicId: ["Topic is unavailable"] }); const result = await studyRepository.create(userId, parsed.data); const sufficient = ensureSufficientQuestions(result.available, parsed.data.questionCount); if (!sufficient.ok) throw new ApplicationError("VALIDATION", sufficient.message, { questionCount: [sufficient.message] }); return result.session!; },
  async getSession(sessionId: string, userId: string): Promise<LearnerSession> { const data = await studyRepository.getOwnedSession(sessionId, userId); if (!data) throw new ApplicationError("NOT_FOUND", "Study session not found."); const attemptsByQuestion = new Map(data.attempts.map((attempt) => [attempt.sessionQuestionId, attempt])); const elapsed = data.session.startedAt ? Math.floor((Date.now() - data.session.startedAt.getTime()) / 1000) : 0; const remainingSeconds = data.session.isTimed && data.session.durationSeconds ? Math.max(0, data.session.durationSeconds - elapsed) : null; return { id: data.session.id, status: data.session.status, isTimed: data.session.isTimed, durationSeconds: data.session.durationSeconds, remainingSeconds, startedAt: data.session.startedAt?.toISOString() ?? null, completedAt: data.session.completedAt?.toISOString() ?? null, examName: data.examName, questions: data.questions.map((item) => { const attempt = attemptsByQuestion.get(item.id); const snapshot = item.snapshot; const correctOptionIds = snapshot.options.filter((option) => option.isCorrect).map((option) => option.id); const feedback: AnswerFeedback | null = attempt ? { selectedOptionIds: attempt.selectedOptionIds, correctOptionIds, isCorrect: attempt.isCorrect, isSkipped: attempt.isSkipped, responseTimeSeconds: attempt.responseTimeSeconds, explanation: snapshot.explanation } : null; return { id: item.id, questionId: item.questionId, order: item.questionOrder, prompt: snapshot.prompt, type: snapshot.type, difficulty: snapshot.difficulty, subjectName: snapshot.subjectName, topicName: snapshot.topicName, options: snapshot.options.map(({ id, text, displayOrder }) => ({ id, text, displayOrder })), correctOptionIds, explanation: snapshot.explanation, feedback }; }) }; },
  async complete(sessionId: string, userId: string, fillSkipped = false) { const result = await studyRepository.complete(sessionId, userId, fillSkipped); if (result.kind === "not_found") throw new ApplicationError("NOT_FOUND", "Study session not found."); if (result.kind === "incomplete") throw new ApplicationError("CONFLICT", `Answer or skip the remaining ${result.remaining} question${result.remaining === 1 ? "" : "s"}.`); if (result.kind === "invalid_status") throw new ApplicationError("CONFLICT", "This session cannot be completed."); return result.session; },
  async completeWithAnswers(userId: string, raw: unknown) { const parsed = completeSessionSchema.safeParse(raw); if (!parsed.success) throw new ApplicationError("VALIDATION", "Invalid session answers.", parsed.error.flatten().fieldErrors); const result = await studyRepository.completeWithAnswers(userId, parsed.data); if (result.kind === "not_found") throw new ApplicationError("NOT_FOUND", "Study session not found."); if (result.kind === "incomplete") throw new ApplicationError("CONFLICT", `Answer or skip the remaining ${result.remaining} question${result.remaining === 1 ? "" : "s"}.`); if (result.kind === "invalid_status") throw new ApplicationError("CONFLICT", "This session cannot be completed."); if (result.kind === "invalid_question") throw new ApplicationError("VALIDATION", "One or more questions do not belong to this session."); if (result.kind === "invalid_options") throw new ApplicationError("VALIDATION", "One or more selected options are invalid."); return result.session; },
  async abandon(sessionId: string, userId: string) { const result = await studyRepository.abandon(sessionId, userId); if (!result) throw new ApplicationError("CONFLICT", "This session cannot be abandoned."); return result; },
  recent: (userId: string, limit?: number) => studyRepository.recent(userId, limit),
};
