"use client";

import { useTransition } from "react";
import { Button, Grid, Paper, PasswordInput, Stack, TextInput, Title } from "@mantine/core";
import { useForm } from "@mantine/form";
import { zod4Resolver } from "mantine-form-zod-resolver";
import { notifications } from "@mantine/notifications";
import { passwordSchema, profileSchema } from "../schemas/user-schema";
import { changePasswordAction, updateProfileAction } from "./actions";

export function AccountSettings({ name, email }: { name: string; email: string }) { const [profilePending, startProfile] = useTransition(); const [passwordPending, startPassword] = useTransition(); const profile = useForm({ initialValues: { name }, validate: zod4Resolver(profileSchema) }); const password = useForm({ initialValues: { currentPassword: "", newPassword: "", confirmPassword: "" }, validate: zod4Resolver(passwordSchema) }); return <Grid><Grid.Col span={{ base: 12, md: 6 }}><Paper className="tabler-card" p="lg"><form onSubmit={profile.onSubmit((values) => startProfile(async () => { const result = await updateProfileAction(values); notifications.show({ color: result.ok ? "green" : "red", message: result.message }); }))}><Stack><Title order={3} fz="md">Profile</Title><TextInput label="Name" {...profile.getInputProps("name")} /><TextInput label="Email" value={email} disabled /><Button type="submit" loading={profilePending} w="fit-content">Update profile</Button></Stack></form></Paper></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><Paper className="tabler-card" p="lg"><form onSubmit={password.onSubmit((values) => startPassword(async () => { const result = await changePasswordAction(values); notifications.show({ color: result.ok ? "green" : "red", message: result.message }); if (result.ok) password.reset(); else if (result.fieldErrors) Object.entries(result.fieldErrors).forEach(([field, messages]) => password.setFieldError(field, messages?.[0])); }))}><Stack><Title order={3} fz="md">Change password</Title><PasswordInput label="Current password" {...password.getInputProps("currentPassword")} /><PasswordInput label="New password" {...password.getInputProps("newPassword")} /><PasswordInput label="Confirm password" {...password.getInputProps("confirmPassword")} /><Button type="submit" loading={passwordPending} w="fit-content">Change password</Button></Stack></form></Paper></Grid.Col></Grid>; }
