"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { Alert, Badge, Button, Group, Paper, Progress, Stack, Text, Title } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconArrowLeft, IconArrowRight, IconCheck, IconClock, IconFlag, IconPlayerSkipForward, IconX } from "@tabler/icons-react";
import { useRouter } from "next/navigation";
import { ConfirmDialog } from "@/shared/ui/confirm-dialog";
import { QuestionRenderer } from "@/shared/ui/question-renderer";
import { formatDuration } from "@/shared/utils/text";
import type { AnswerFeedback, LearnerSession } from "../types/session-types";
import { abandonSessionAction, completeSessionAction, submitAnswerAction } from "./actions";

export function SessionRunner({ initialSession }: { initialSession: LearnerSession }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const firstUnanswered = initialSession.questions.findIndex((item) => !item.feedback); const [index, setIndex] = useState(firstUnanswered >= 0 ? firstUnanswered : 0); const [feedback, setFeedback] = useState<Record<string, AnswerFeedback>>(Object.fromEntries(initialSession.questions.filter((item) => item.feedback).map((item) => [item.id, item.feedback!]))) ; const [selections, setSelections] = useState<Record<string, string[]>>(Object.fromEntries(initialSession.questions.map((item) => [item.id, item.feedback?.selectedOptionIds ?? []]))); const [abandonOpen, setAbandonOpen] = useState(false); const startedQuestionAt = useRef(0); const completing = useRef(false);
  const currentBase = initialSession.questions[index]; const current = { ...currentBase, feedback: feedback[currentBase.id] ?? null }; const answered = Object.keys(feedback).length; const allAnswered = answered === initialSession.questions.length;
  const [remaining, setRemaining] = useState<number | null>(initialSession.remainingSeconds);
  useEffect(() => { startedQuestionAt.current = Date.now(); }, [index]);
  useEffect(() => { if (remaining === null) return; if (remaining <= 0 && !completing.current) { completing.current = true; startTransition(async () => { const result = await completeSessionAction(initialSession.id, true); if (result.ok) router.replace(`/study/session/${initialSession.id}/summary`); else { completing.current = false; notifications.show({ color: "red", message: result.message }); } }); return; } const timer = window.setInterval(() => setRemaining((value) => value === null ? null : Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [remaining, initialSession.id, router]);
  const submit = (skip = false) => startTransition(async () => { const result = await submitAnswerAction({ sessionId: initialSession.id, sessionQuestionId: current.id, selectedOptionIds: skip ? [] : selections[current.id] ?? [], responseTimeSeconds: Math.min(3600, Math.max(0, Math.round((Date.now() - startedQuestionAt.current) / 1000))), skip }); if (result.ok) setFeedback((value) => ({ ...value, [current.id]: result.data })); else notifications.show({ color: "red", message: result.message }); });
  const finish = () => startTransition(async () => { const result = await completeSessionAction(initialSession.id); if (result.ok) router.push(`/study/session/${initialSession.id}/summary`); else notifications.show({ color: "red", message: result.message }); });
  const abandon = () => startTransition(async () => { const result = await abandonSessionAction(initialSession.id); if (result.ok) router.push("/study"); else notifications.show({ color: "red", message: result.message }); });
  return <Stack gap="lg"><Paper className="tabler-card" p="md"><Group justify="space-between"><div><Text fz="sm" c="dimmed">{initialSession.examName}</Text><Text fw={600}>Question {index + 1} of {initialSession.questions.length}</Text></div>{remaining !== null && <Badge size="lg" variant="light" color={remaining < 60 ? "red" : "blue"} leftSection={<IconClock size={15} />}>{formatDuration(remaining)}</Badge>}</Group><Progress value={((index + 1) / initialSession.questions.length) * 100} mt="md" size="sm" /></Paper>
  <Paper className="tabler-card" p={{ base: "md", sm: "xl" }}><Stack gap="lg"><Group gap="xs"><Badge variant="light">{current.subjectName}</Badge><Badge variant="light" color="gray">{current.topicName}</Badge><Badge variant="light" color={current.difficulty === "hard" ? "red" : current.difficulty === "medium" ? "yellow" : "green"}>{current.difficulty}</Badge></Group><Title order={2} fz={{ base: 20, sm: 24 }} className="question-copy">{current.prompt}</Title><QuestionRenderer question={current} selected={selections[current.id] ?? []} onChange={(ids) => setSelections((value) => ({ ...value, [current.id]: ids }))} disabled={Boolean(current.feedback) || pending} />{current.feedback && <Alert color={current.feedback.isSkipped ? "blue" : current.feedback.isCorrect ? "green" : "red"} icon={current.feedback.isCorrect ? <IconCheck size={19} /> : current.feedback.isSkipped ? <IconPlayerSkipForward size={19} /> : <IconX size={19} />} title={current.feedback.isSkipped ? "Question skipped" : current.feedback.isCorrect ? "Correct answer" : "Not quite"}><Text className="question-copy">{current.feedback.explanation || "No explanation has been provided."}</Text></Alert>}</Stack></Paper>
  <Group justify="space-between" wrap="wrap"><Group><Button variant="default" leftSection={<IconArrowLeft size={16} />} disabled={index === 0} onClick={() => setIndex((value) => value - 1)}>Previous</Button><Button variant="default" rightSection={<IconArrowRight size={16} />} disabled={index === initialSession.questions.length - 1} onClick={() => setIndex((value) => value + 1)}>Next</Button></Group><Group>{!current.feedback && <><Button variant="light" color="gray" leftSection={<IconPlayerSkipForward size={16} />} onClick={() => submit(true)} loading={pending}>Skip</Button><Button onClick={() => submit(false)} loading={pending} disabled={(selections[current.id] ?? []).length === 0}>Submit answer</Button></>}{allAnswered && <Button color="green" leftSection={<IconFlag size={16} />} onClick={finish} loading={pending}>Finish session</Button>}<Button variant="subtle" color="red" onClick={() => setAbandonOpen(true)}>Abandon</Button></Group></Group>
  <Text fz="sm" c="dimmed" ta="center">{answered} of {initialSession.questions.length} answered or skipped</Text><ConfirmDialog opened={abandonOpen} onClose={() => setAbandonOpen(false)} onConfirm={abandon} title="Abandon this session?" message="Submitted attempts will remain in your history, but unanswered questions will not count toward progress." confirmLabel="Abandon session" loading={pending} /></Stack>;
}
