"use client";

import { useMemo, useTransition } from "react";
import { Alert, Button, Grid, NumberInput, Paper, Select, Stack, Switch, Text, Title } from "@mantine/core";
import { useForm } from "@mantine/form";
import { zod4Resolver } from "mantine-form-zod-resolver";
import { notifications } from "@mantine/notifications";
import { IconPlayerPlay } from "@tabler/icons-react";
import { useRouter } from "next/navigation";
import type { Exam, Subject, Topic } from "@/infrastructure/database/schema";
import type { ApplicationSettings } from "@/modules/settings/schemas/settings-schema";
import { createSessionSchema } from "../schemas/study-schema";
import { createSessionAction } from "./actions";

export function SessionCreator({ exams, subjects, topics, settings, initialSubjectId }: { exams: Exam[]; subjects: Subject[]; topics: Topic[]; settings: ApplicationSettings; initialSubjectId?: string }) {
  const initialSubject = subjects.find((item) => item.id === initialSubjectId); const router = useRouter(); const [pending, startTransition] = useTransition(); const form = useForm({ initialValues: { examId: initialSubject?.examId ?? exams[0]?.id ?? "", subjectId: initialSubject?.id ?? "", topicId: "", questionCount: settings.defaultQuestionCount, difficulty: "", isTimed: false, durationMinutes: 20 }, validate: zod4Resolver(createSessionSchema) }); const subjectOptions = useMemo(() => subjects.filter((item) => item.examId === form.values.examId), [subjects, form.values.examId]); const topicOptions = useMemo(() => topics.filter((item) => item.subjectId === form.values.subjectId && !item.parentTopicId), [topics, form.values.subjectId]);
  const submit = form.onSubmit((values) => startTransition(async () => { const result = await createSessionAction(values); if (result.ok) router.push(`/study/session/${result.data.id}`); else { notifications.show({ color: "red", message: result.message }); if (result.fieldErrors) Object.entries(result.fieldErrors).forEach(([field, messages]) => form.setFieldError(field, messages?.[0])); } }));
  return <Paper className="tabler-card session-creator-card" data-accent="violet" p="lg"><form onSubmit={submit} noValidate><Stack><Title order={3} fz="md">Configure a session</Title>{exams.length === 0 && <Alert color="orange">No active exams currently have study content.</Alert>}<Grid><Grid.Col span={{ base: 12, md: 6 }}><Select label="Exam" required searchable data={exams.map((item) => ({ value: item.id, label: item.name }))} value={form.values.examId} onChange={(value) => { form.setFieldValue("examId", value ?? ""); form.setFieldValue("subjectId", ""); form.setFieldValue("topicId", ""); }} error={form.errors.examId} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><Select data-testid="study-subject" label="Subject" description="Optional" clearable searchable data={subjectOptions.map((item) => ({ value: item.id, label: item.name }))} value={form.values.subjectId} onChange={(value) => { form.setFieldValue("subjectId", value ?? ""); form.setFieldValue("topicId", ""); }} error={form.errors.subjectId} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><Select label="Topic" description="Optional" clearable disabled={!form.values.subjectId} data={topicOptions.map((item) => ({ value: item.id, label: item.name }))} {...form.getInputProps("topicId")} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><Select label="Difficulty" description="Optional" clearable data={[{ value: "easy", label: "Easy" }, { value: "medium", label: "Medium" }, { value: "hard", label: "Hard" }]} {...form.getInputProps("difficulty")} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><NumberInput label="Number of questions" min={1} max={100} required {...form.getInputProps("questionCount")} /></Grid.Col><Grid.Col span={{ base: 12, md: 6 }}><NumberInput label="Duration (minutes)" min={1} max={300} disabled={!form.values.isTimed} required={form.values.isTimed} {...form.getInputProps("durationMinutes")} /></Grid.Col></Grid>{settings.allowTimedSessions && <Switch label="Timed session" description="A countdown will start when the session is created." {...form.getInputProps("isTimed", { type: "checkbox" })} />}<Button type="submit" data-haptic="medium" leftSection={<IconPlayerPlay size={17} />} loading={pending} disabled={!exams.length} w="fit-content">Start study session</Button><Text fz="xs" c="dimmed">Your question list is fixed when the session starts and can be resumed after a refresh.</Text></Stack></form></Paper>;
}
